version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: followinvestments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build:
      context: ./backend/FollowInvestments.Api
      dockerfile: Dockerfile
    ports:
      - "9900:9900"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:9900
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=followinvestments;Username=postgres;Password=postgres

  frontend:
    build:
      context: ./frontend/investment-dashboard
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    depends_on:
      - api
